### ISSUE TITLE
Registered account will show up as public hub in the TAG

### ISSUE THREAD

**Issue by Sopor-** [pavel-pimenov/flylinkdc-r5xx#1644]
In FlyLink r504-beta-x64 build 19849 it will show a registered hub as a public. This is how it looks in the TAG `<FlylinkDC++ r504-beta-x64-19849,M:P-,H:1/0/0,S:3>`
but it should be
`<FlylinkDC++ r504-beta-x64-19849,M:P-,H:0/1/0,S:3>`
The hub soft (Luadch) will detect it as 1/1/0.
It haven't been like this before so it must have happening in some of the latest version.
I don't understand russian so if this is already reported you have to excuse me :)

**Comment by SCALOlaz** [comment]
Yes, it is a problem. Probably from the time of StrongDC++
To this day, few people are concerned about this bug. :)
( hubs without registration / hubs registered / hubs with op key )

Да, это проблема. Вероятно со времён StrongDC++
До этого дня мало кого беспокоил этот баг :)
( хабов без регистрации / с регистрацией / с правами оператора )

**Comment by Sopor-** [comment]
So you won't fix it?

**Comment by pavel-pimenov** [comment]
ApexDC++: H:1/0/0
![default](https://cloud.githubusercontent.com/assets/920705/21449923/3166aab8-c903-11e6-9f76-2f9f678e3e63.png)

**Comment by SCALOlaz** [comment]
to Sopor:
About two months ago, has been corrected

**Comment by Sopor-** [comment]
When i connect with ApexDC i get 0/0/0 and after a few seconds it will change to 0/1/0. FlyLink have 1/0/0 and even after 30-60 minutes it still show 1/0/0.
FlylinkDC++ r504-beta-x64 build 20255 / 0.785
